import os
import json
import requests
from datetime import date, timedelta
from dotenv import load_dotenv
from email_utils import send_email
from nvd_client import fetch_recent_nvd

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")
SEEN_FILE = "seen_cves.json"

CISA_KEV_URL = "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json"
HF_API_URL = "https://router.huggingface.co/hf-inference/models/facebook/bart-large-cnn"


def load_seen():
    if not os.path.exists(SEEN_FILE):
        return set()

    with open(SEEN_FILE, "r") as f:
        return set(json.load(f))


def save_seen(cves):
    with open(SEEN_FILE, "w") as f:
        json.dump(sorted(list(cves)), f, indent=2)


def fetch_cisa_kev():
    res = requests.get(CISA_KEV_URL, timeout=20)
    res.raise_for_status()
    return res.json()["vulnerabilities"]


def summarize_with_hf(text):
    headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json"
    }

    payload = {
        "inputs": text,
        "parameters": {
            "max_length": 80,
            "min_length": 25,
            "do_sample": False
        }
    }

    res = requests.post(HF_API_URL, headers=headers, json=payload, timeout=60)

    if res.status_code != 200:
        print("HF ERROR:", res.status_code, res.text)
        return "Summary unavailable. Hugging Face API error."

    data = res.json()
    return data[0]["summary_text"]


def is_recent_vulnerability(vuln):
    today = date.today()
    yesterday = today - timedelta(days=1)

    date_added = vuln.get("dateAdded")

    return date_added in {
        today.isoformat(),
        yesterday.isoformat()
    }


def main():
    seen = load_seen()
    cisa_vulns = fetch_cisa_kev()
    nvd_vulns = fetch_recent_nvd(days=2)

    vulnerabilities = cisa_vulns + nvd_vulns

    new_items = []

    for vuln in vulnerabilities:

        source = vuln.get("source", "CISA KEV")
        severity = vuln.get("severity", "Known Exploited")
        cvss_score = vuln.get("cvssScore", "N/A")
        cve_id = vuln.get("cveID")

        if is_recent_vulnerability(vuln) and cve_id not in seen:
            new_items.append(vuln)

    if not new_items:
        print("No new recent vulnerabilities found.")
        return

    print(f"Found {len(new_items)} new recent vulnerabilities.\n")

    email_sections = []

    for vuln in new_items[:5]:
        Source: {source}
        Severity: {severity}
        CVSS_Score: {cvss_score}
        cve_id = vuln.get("cveID")
        vendor = vuln.get("vendorProject")
        product = vuln.get("product")
        name = vuln.get("vulnerabilityName")
        notes = vuln.get("notes", "")
        action = vuln.get("requiredAction")
        due_date = vuln.get("dueDate")
        date_added = vuln.get("dateAdded")

        text = f"""
CVE: {cve_id}
Vendor: {vendor}
Product: {product}
Vulnerability: {name}
Notes: {notes}
Required Action: {action}
Due Date: {due_date}
Date Added: {date_added}
"""

        summary = summarize_with_hf(text)

        section = f"""
----------------------------------------

CVE: {cve_id}
Vendor/Product: {vendor} {product}
Issue: {name}
Date Added: {date_added}

AI Summary:
{summary}

Required Action:
{action}

Due Date:
{due_date}
"""

        email_sections.append(section)

        print("=" * 60)
        print(section)

        seen.add(cve_id)

    final_email_body = f"""
🚨 VulnBot Vulnerability Report

Found {len(new_items)} new recent vulnerabilities.
Showing latest {min(5, len(new_items))}:

{''.join(email_sections)}

Generated by VulnBot.
"""

    send_email(
        subject=f"🚨 VulnBot Report: {min(5, len(new_items))} Recent Vulnerabilities",
        body=final_email_body
    )

    save_seen(seen)


if __name__ == "__main__":
    main()