def build_vuln_text(vuln):
    return f"""
CVE: {vuln.get("cveID")}
Source: {vuln.get("source")}
Vendor: {vuln.get("vendorProject")}
Product: {vuln.get("product")}
Vulnerability: {vuln.get("vulnerabilityName")}
Severity: {vuln.get("severity")}
CVSS Score: {vuln.get("cvssScore")}
Notes: {vuln.get("notes")}
Required Action: {vuln.get("requiredAction")}
Due Date: {vuln.get("dueDate")}
Date Added: {vuln.get("dateAdded")}
"""


def build_email_report(sections, total_count):
    return f"""
🚨 VulnBot AI Security Analyst Report

Found {total_count} recent vulnerabilities.
Showing latest {len(sections)}:

{''.join(sections)}

Generated by VulnBot.
"""


def build_email_section(vuln, analysis):
    return f"""
----------------------------------------

CVE: {vuln.get("cveID")}
Source: {vuln.get("source")}
Vendor/Product: {vuln.get("vendorProject")} {vuln.get("product")}
Issue: {vuln.get("vulnerabilityName")}
Severity: {vuln.get("severity")}
CVSS Score: {vuln.get("cvssScore")}
Date Added: {vuln.get("dateAdded")}

AI Security Analysis:
{analysis}

Required Action:
{vuln.get("requiredAction")}

Due Date:
{vuln.get("dueDate")}
"""