def build_html_email_report(items, total_count):
    rows = ""

    for item in items:
        vuln = item["vuln"]
        analysis = item["analysis"]

        rows += f"""
        <div style="border:1px solid #ddd; border-radius:10px; padding:16px; margin-bottom:18px;">
            <h2>{vuln.get("cveID")}</h2>
            <p><b>Source:</b> {vuln.get("source")}</p>
            <p><b>Vendor/Product:</b> {vuln.get("vendorProject")} {vuln.get("product")}</p>
            <p><b>Issue:</b> {vuln.get("vulnerabilityName")}</p>
            <p><b>CVSS:</b> {vuln.get("cvssScore")}</p>

            <hr>

            <p><b>What happened:</b> {analysis.get("what_happened")}</p>
            <p><b>Who is affected:</b> {analysis.get("who_is_affected")}</p>
            <p><b>Personal relevance:</b> {analysis.get("personal_relevance")}</p>
            <p><b>Reason:</b> {analysis.get("relevance_reason")}</p>
            <p><b>Risk level:</b> {analysis.get("risk_level")}</p>
            <p><b>Should I care?</b> {analysis.get("should_i_care")}</p>
            <p><b>Recommended action:</b> {analysis.get("recommended_action")}</p>
        </div>
        """

    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; color:#222;">
        <h1>🚨 VulnBot AI Security Report</h1>
        <p>Found <b>{total_count}</b> recent vulnerabilities. Showing latest <b>{len(items)}</b>.</p>
        {rows}
        <p style="font-size:12px;color:#777;">Generated by VulnBot.</p>
    </body>
    </html>
    """